OCD_LINKS = {
            "ocd_artbase": ["prop_class"],
            "ocd_article": ["short_textnr", "long_textnr", "rel_obj", "scheme_id"],
            "ocd_articletaxes": ["tax_id"],
            "ocd_artlongtext": ["textnr"],
            "ocd_artshorttext": ["textnr"],
            "ocd_codescheme": ["scheme_id"],
            "ocd_price": ["rounding_id"],
            "ocd_pricetext": ["textnr"],
            "ocd_propclasstext": ["textnr"],
            "ocd_property": ["prop_textnr", "hint_text_id", "prop_class", "rel_obj"],
            "ocd_propertyclass": ["textnr", "prop_class"],
            "ocd_propertytext": ["textnr"],
            "ocd_propertyvalue": ["pval_textnr", "rel_obj", "prop_class"],
            "ocd_prophinttext": ["textnr"],
            "ocd_propvaluetext": ["textnr"],
            "ocd_relation": ["rel_name"],
            "ocd_relationobj": ["rel_obj", "rel_name"],
            "ocd_rounding": ["id"],
            "ocd_taxscheme": ["tax_id"],

            "optproperty_dat": ["prop_class", "prop_textnr"],
            "optpropvalue_txt": ["textnr"],
        }